default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: sabrinawdesmond

development:
  <<: *default
  database: wherebnb_development

test:
  <<: *default
  database: wherebnb_test

production:
  <<: *default
  database: wherebnb_production
